name: Prepare

on:
  pull_request:
    types: [synchronize, opened, reopened]

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: ESLint
    needs: label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v2
      - name: install
        run: yarn install --check-files --frozen-lockfile
      - name: lint
        run: yarn lint
  test:
    name: Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v2
      - name: install
        run: yarn install --check-files --frozen-lockfile
      - name: test
        run: yarn test
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v2
      - name: install
        run: yarn install --check-files --frozen-lockfile
      - name: build
        run: yarn build

